#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor -d 1 2 3 4 5 6
# bspc monitor DP-3 -d 1 2 3
# bspc monitor HDMI-0 -d 4 5 6

bspc config border_width        1.5
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Windows start state 
bspc rule -a Steam state=floating 

# Colors
bspc config focused_border_color        "$color15"
bspc config normal_border_color         "$color1"
bspc config active_border_color         "$color2"

# screen config
# xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-3 --mode 1920x1080 --rotate normal --left-of HDMI-0
xrandr --output Virtual-1 --primary --mode 1920x1080 --rotate normal

# Wallpaper
## Random
# wal -i ~/Imagens/wallpapers/	
## Restores last walpaper used
wal -R

# Bar
sh ~/.config/polybar/launch.sh

# Trasnperacy
# picom --config ~/.config/picom/picom.conf &
# picom --experimental-backends -b &
# note: picom only suports transperacy above v9

# Blue Light Filter
redshift -P -O 3200

# Notifications
notify-send " Welcome Back! "

# Syncthing 
syncthing &
